Break dependency on python/dist from python/BUILD.bazel
This package referenced things in python/dist, which is not loadable
from other projects since pip deps are marked as `dev_dependency=True`.
This resulted in this error downstream:

```
ERROR: Evaluation of query "deps(//...)" failed: preloading transitive closure failed: error loading package '@@protobuf+//python/dist': Unable to find package for @@[unknown repo 'protobuf_pip_deps' requested from @@protobuf+]//:requirements.bzl: The repository '@@[unknown repo 'protobuf_pip_deps' requested from @@protobuf+]' could not be resolved: No repository visible as '@protobuf_pip_deps' from repository '@@protobuf+'.
```

Since this was only used to determine if the target is macOS, we can use
the platforms definition directly instead.