Add missing cstdint include to port.h
Fixes compile errors with GCC 13.

port.h:186:67: error: ‘uint32_t’ was not declared in this scope
port.h:187:67: error: ‘uint64_t’ was not declared in this scope