Add missing declaration in protobuf_headers
To prevent us from getting such error with sandbox or remote execution:
```
bazel-out/k8-opt/genfiles/tensorflow/core/lib/core/error_codes.pb.h:10:40: fatal error: google/protobuf/port_def.inc: No such file or directory
 #include <google/protobuf/port_def.inc>
                                        ^
```