Add the `experimental_use_cc_common_link` flag for Rust
Upgrading to rules_rust 0.54.1 seems to have fixed some of our Rust linking
problems, but not all, so this change adds back in the
`--@rules_rust//rust/settings:experimental_use_cc_common_link=True` flag.

This fixes some local build errors like the following:
```
$ bazel build //rust/test/shared:bad_names_cpp_test

...

  = note: bazel-out/k8-fastbuild/bin/rust/test/shared/_ambiguous_libs/bad_names_cpp_test/libport-330124825.a(port.pic.o):port.cc:function google::protobuf::internal::CounterMap():(.text+0xe6): error: undefined reference to 'atexit'
```

PiperOrigin-RevId: 702380176