text_format_decode_data: Add missing cstdint include
Fixes compile errors with GCC 13

../protobuf-22.3/src/google/protobuf/compiler/objectivec/text_format_decode_data.h:59:18: error: 'int32_t' has not been declared