Fixes a few Closure Compiler warnings in the generated JavaScript code.
Specifically:
  Error: Type is already not null. Please remove the redundant !.
  Cause: * @return {!boolean}

  Error: Name Array in JSDoc is implicitly nullable, and is discouraged by the
         guide. Please add a ! to make it non-nullable, or a ? to make it
         explicitly nullable.
  Cause: * @param {Array=} opt_data Optional initial data array, typically from

  Error: Function must have JSDoc.
  Cause: $PROTO_CLASS.prototype.clear$FIELD_NAME = function() {