Change back to using String instead of Class as the argument on the Poison Pill.
The reason to change this back is that one purpose of this method to provide a good message when e.g. someone tries to use 4.33.0 gencode against 4.30 runtime. The 4.30 runtime only has the `String` argument method, so by having new gencode try to call the `Class` one it will result in ABI behavior of a NoSuchMethodError instead of getting the clean message when that 'bad direction skew' happens.

This partial-rollback tries to retain the benefit of avoiding the small cost of the .class.getName() call by having new gencode simply emit the name as a string literal like `"MyMessageProto"` instead of  `MyMessageProto.class.getName()` when calling the poison pill.

Because we didn't do any open source releases with this change quite yet, we can remove the `Class` overload here instead of it having to linger forever.

PiperOrigin-RevId: 813433985