Fix lambda capture compiler error with c++20 (#1502)
When compiling with C++20, the following error is produced:

```
upb/mini_table.hpp:63:22: note: add explicit 'this' or '*this' capture
upb/mini_table.hpp: In lambda function:
upb/mini_table.hpp:71:22: error: implicit capture of 'this' via '[=]' is deprecated in C++20 [-Werror=deprecated]
   71 |     return appender_([=](char* buf) {
```

In C++20, it is no longer allowed to implicitly capture 'this' in a
lambda using [=].

This commit explicitly captures required values in the appropriate
lambdas and removes all uses of [=] with lambdas.