Add missing cstdint include to port.h (#12331)
Fixes compile errors with GCC 13.

port.h:186:67: error: ‘uint32_t’ was not declared in this scope
port.h:187:67: error: ‘uint64_t’ was not declared in this scope

Closes #12331

COPYBARA_INTEGRATE_REVIEW=https://github.com/protocolbuffers/protobuf/pull/12331 from jonaski:cstdint 9bef4494786edc2b214342f20137a28b457fcaee
PiperOrigin-RevId: 519208789